apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins-test
  name: jenkins-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-test
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
        - image: m7moxd/jenkins_test:${BUILD_NUMBER}
          name: jenkins-test
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: {}
